### ISSUE TITLE
Update Inflector package

### ISSUE THREAD

**Issue by abdulrahman19** [deoliveiralucas/array-keys-case-transform#3]
Hi,

Can you please update `ICanBoogie/Inflector` to version [`2.0.0`](https://github.com/ICanBoogie/Inflector/tree/v2.0.0) to be compatible with `PHP 7`.

thanks

**Comment by deoliveiralucas** [comment]
Hi @abdulrahman19,

It was updated on PR #4 to v1.1.0.

Tks :)
